//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Obiektówka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obliczenia
    {
        public int Id { get; set; }
        public string Obliczenia1 { get; set; }
        public string Wyniki { get; set; }
    }
}
